fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        nodes-cache:
            types:
                node-cache:
                    properties:
                        id:
                            type: integer
                        name:
                            type: keyword
                        description:
                            type: text
                            index: false
                        formattedName:
                            type: keyword
                        weight:
                            type: integer
                        nodeType:
                            type: integer
                        relationTypes:
                            type: nested
                            properties:
                                id:
                                    type: integer
                                code:
                                    type: keyword
                                description:
                                    type: text
                                name:
                                    type: keyword
                                relations:
                                    type: nested
                                    properties:
                                        in:
                                            type: nested
                                            properties:
                                                id:
                                                    type: integer
                                                weight:
                                                    type: integer
                                                node:
                                                    type: object
                                                    properties:
                                                        id:
                                                            type: integer
                                                        name:
                                                            type: keyword
                                                        formattedName:
                                                            type: keyword
                                                        nodeType:
                                                            type: integer
                                                        weight:
                                                            type: integer
                                        out:
                                            type: nested
                                            properties:
                                                id:
                                                    type: integer
                                                weight:
                                                    type: integer
                                                node:
                                                    type : object
                                                    properties:
                                                        formattedName:
                                                            type: keyword
                                                        id:
                                                            type: integer
                                                        name:
                                                            type: keyword
                                                        nodeType:
                                                            type: integer
                                                        weight:
                                                            type: integer
                        nodeTypes:
                            type: nested
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: text
                    persistence:
                        driver: orm
                        model: Garad\PlatformBundle\Entity\NodeCache
                        finder: ~
                        provider: ~