<?php

namespace Garad\PlatformBundle\Repository;

/**
 * NodeCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeCacheRepository extends \Doctrine\ORM\EntityRepository
{

}
