garad_jdm_redirect:
    path:      /
    defaults: { _controller: GaradPlatformBundle:Jdm:redirect }


garad_jdm_home:
    path:      /jdm/
    defaults: { _controller: GaradPlatformBundle:Jdm:index }

garad_jdm_search:
    path:      /jdm/{word}
    defaults: { _controller: GaradPlatformBundle:Jdm:search }


