
hello_the_world:
    path:     /hello-world
    defaults: { _controller: GaradPlatformBundle:Advert:index }

bye_the_world:
    path:     /bye
    defaults: { _controller: GaradPlatformBundle:Advert:exit }



garad_jdm_home:
    path:      /jdm
    defaults: { _controller: GaradPlatformBundle:Jdm:index }

garad_jdm_home2:
    path:      /jdm/
    defaults: { _controller: GaradPlatformBundle:Jdm:goindex }

garad_jdm_search:
    path:      /jdm/{word}
    defaults: { _controller: GaradPlatformBundle:Jdm:search }


